# Generated by Django 6.0 on 2026-01-04 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpboard', '0002_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='helpboard.category'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='ProblemSolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvers', to='helpboard.problem')),
                ('solver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('problem', 'solver')},
            },
        ),
    ]
