# Generated by Django 6.0 on 2026-01-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpboard', '0003_alter_problem_author_alter_problem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
