# Generated by Django 6.0 on 2026-01-05 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpboard', '0004_problem_solved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='problemsolver',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='problem_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Resolved')], default=0),
        ),
        migrations.AlterField(
            model_name='problemsolver',
            name='solver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solver_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status'], name='helpboard_p_status_a54162_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['category'], name='helpboard_p_categor_91efaf_idx'),
        ),
    ]
