# Generated by Django 6.0 on 2026-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpboard', '0006_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='location',
            field=models.CharField(blank=True, help_text='Location where the problem exists', max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
